In [3]:
# !pip install pandas-profiling

In [5]:
# !pip install spacy

In [7]:
# !pip install en_core_web_sm-3.1.0-py3-none-any.whl

In [8]:
import spacy
import en_core_web_sm
nlp = spacy.load("en_core_web_sm")

In [9]:
import pandas as pd

In [10]:
df_combined_web_iva_search = pd.read_csv("s3://adl-core-sagemaker-studio/external/IVA/combined1.csv")

/tmp/ipykernel_11532/1795762148.py:1: DtypeWarning: Columns (28,101,118) have mixed types. Specify dtype option on import or set low_memory=False.
  df_combined_web_iva_search = pd.read_csv("s3://adl-core-sagemaker-studio/external/IVA/combined1.csv")

In [11]:
df_combined_web_iva_search.head()

,agent_entitlement_client_name,agent_entitlement_access_key,channel,companytracking_clientid,companytracking_companyid,companytracking_companyname,companytracking_multitenantid,entry_id,entry_order,entry_type,...,action_type,load_timestamp,source_system_code,mobile_app_device_type,page_load_elapsed_time,mobile_app_type,session_create_date_cst_timezone_partition,platform_id_y,search_text,search_results
0,Enterprise,00000000-0000-0000-0000-000000000000,Web,1141,jci,Johnson Controls Inc,NaN,2584351,3,Click Unit Link,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Enterprise,00000000-0000-0000-0000-000000000000,Web,8666,bestbuy,Best Buy,NaN,2657214,6,Click Unit Link,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Enterprise,00000000-0000-0000-0000-000000000000,Web,8053,sodexo,sodexo,NaN,2743663,4,Click Unit Link,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Enterprise,00000000-0000-0000-0000-000000000000,Web,8053,sodexo,sodexo,NaN,2743662,3,Click Unit Link,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Huntington Ingalls Industries Inc.,376b48f5-f9f3-4911-9e73-7d40c25b47c7,Web,15757,hii,Huntington Ingalls Industries,NaN,10566463,2,Typed Input,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df_combined_web_iva_search.shape

(315251, 169)

In [13]:
df_combined_web_iva_search.drop_duplicates(inplace=True)

In [14]:
df_combined_web_iva_search.shape

(315251, 169)

In [15]:
df_combined_web_iva_search.head()

,agent_entitlement_client_name,agent_entitlement_access_key,channel,companytracking_clientid,companytracking_companyid,companytracking_companyname,companytracking_multitenantid,entry_id,entry_order,entry_type,...,action_type,load_timestamp,source_system_code,mobile_app_device_type,page_load_elapsed_time,mobile_app_type,session_create_date_cst_timezone_partition,platform_id_y,search_text,search_results
0,Enterprise,00000000-0000-0000-0000-000000000000,Web,1141,jci,Johnson Controls Inc,NaN,2584351,3,Click Unit Link,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Enterprise,00000000-0000-0000-0000-000000000000,Web,8666,bestbuy,Best Buy,NaN,2657214,6,Click Unit Link,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Enterprise,00000000-0000-0000-0000-000000000000,Web,8053,sodexo,sodexo,NaN,2743663,4,Click Unit Link,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Enterprise,00000000-0000-0000-0000-000000000000,Web,8053,sodexo,sodexo,NaN,2743662,3,Click Unit Link,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Huntington Ingalls Industries Inc.,376b48f5-f9f3-4911-9e73-7d40c25b47c7,Web,15757,hii,Huntington Ingalls Industries,NaN,10566463,2,Typed Input,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
df_combined_web_iva_search.columns.to_list() # 'input', 'session_id','person_internal_id','client_id',
# 'yyyymm',

['agent_entitlement_client_name',
 'agent_entitlement_access_key',
 'channel',
 'companytracking_clientid',
 'companytracking_companyid',
 'companytracking_companyname',
 'companytracking_multitenantid',
 'entry_id',
 'entry_order',
 'entry_type',
 'input',
 'inputnotunderstood_type',
 'knowledge_category',
 'knowledge_category_path',
 'navigation_url',
 'next_unit_hit',
 'previous_unit_hit',
 'response_condition',
 'response_text',
 'session_id',
 'session_start_utc',
 'session_start_cst',
 'transactioncontribution_factor',
 'unit_name',
 'agent_session_id',
 'time_submitted_utc',
 'time_submitted_cst',
 'unit_id',
 'response_name',
 'related_links',
 'matched_search_criteria',
 'agent_user_id',
 'escalation_type',
 'companytracking_personalid',
 'person_internal_id',
 'client_id',
 'prompting_task',
 'prompting_task_step',
 'other_active_tasks',
 'complete_tasks',
 'cancelled_tasks',
 'conversation_rating_random_sample_queue',
 'conversation_rating_all_conversations_queue',
 'conversation_rating_reason_random_sample_queue',
 'conversation_rating_comment_random_sample_queue',
 'conversation_rating_reason_all_conversations_queue',
 'conversation_rating_comment_all_conversations_queue',
 'entry_rating_random_sample_queue',
 'entry_rating_reason_random_sample_queue',
 'entry_rating_comment_random_sample_queue',
 'entry_rating_all_conversations_queue',
 'entry_rating_reason_all_conversations_queue',
 'entry_rating_comment_all_conversations_queue',
 'entry_feedback_rating_end_user_feedback_queue',
 'entry_feedback_rating_reason_end_user_feedback_queue',
 'entry_feedback_rating_comment_end_user_feedback_queue',
 'fpml_version',
 'last_unit_in_conversation',
 'transactionnegation',
 'knowledgetie_units_0_label',
 'knowledgetie_units_0_unit_id',
 'referralaccepted_destchannel',
 'referralaccepted_destqueue',
 'load_ts',
 'language',
 'reporting_events',
 'yyyymm',
 'web_page_detail_event_key',
 'web_page_detail_event_key_columns',
 'client_key',
 'implementation_key',
 'participant_key',
 'platform_id_x',
 'implementation_hierarchy_key',
 'person_id',
 'platform_person_internal_id',
 'source_person_internal_id',
 'source_person_id',
 'person_birth_date',
 'person_age',
 'person_gender',
 'person_employment_status',
 'person_state',
 'person_union_vs_non_union',
 'person_salary',
 'person_eeo',
 'admin_id',
 'user_id_type',
 'source_global_session_id',
 'source_global_session_create_timestamp',
 'global_session_id',
 'global_session_create_timestamp_cst_timezone',
 'web_session_id',
 'session_create_timestamp_cst_timezone',
 'web_user_type_id',
 'web_user_type_description',
 'web_user_system_id',
 'remote_ip_address',
 'page_name',
 'page_visit_date_cst_timezone',
 'page_visit_timestamp_cst_timezone',
 'portlet_name',
 'business_page_name',
 'page_domain',
 'page_type_code',
 'page_type',
 'page_web_type_description',
 'page_sequence_number',
 'request_method_description',
 'global_session_end_page_name',
 'global_session_end_portlet_name',
 'global_session_end_page_process_name',
 'global_session_end_business_page_name',
 'global_session_end_page_domain',
 'global_session_end_page_type_code',
 'global_session_end_page_type',
 'global_session_end_page_web_type_description',
 'link_id',
 'link_destination_url',
 'link_id_display',
 'link_external_info',
 'link_flow',
 'link_type_code',
 'link_type_description',
 'business_link_id',
 'web_conversation_id',
 'web_channel_application_code',
 'web_channel_application_description',
 'web_channel_application_version',
 'initial_web_channel_application_code',
 'initial_web_channel_application_description',
 'initial_web_channel_application_version',
 'host_name_description',
 'web_authentication_level_id',
 'web_authentication_level_description',
 'web_security_method_description',
 'web_logon_type_description',
 'web_device_type',
 'browser_language',
 'page_visit_duration',
 'web_session_page_indicator',
 'outbound_page_link_indicator',
 'hint_page_indicator',
 'error_page_indicator',
 'logon_page_indicator',
 'logoff_page_indicator',
 'last_visited_page_indicator',
 'password_reset_page_indicator',
 'hm_enrollment_abandoned_indicator',
 'hm_enrollment_initiated_indicator',
 'hm_enrollment_completed_indicator',
 'web_page_abandoned_indicator',
 'web_chat_request_indicator',
 'page_slide_indicator',
 'web_page_payload_size',
 'page_process_name',
 'page_process_detail',
 'iva_used_indicator',
 'event_position',
 'action_type',
 'load_timestamp',
 'source_system_code',
 'mobile_app_device_type',
 'page_load_elapsed_time',
 'mobile_app_type',
 'session_create_date_cst_timezone_partition',
 'platform_id_y',
 'search_text',
 'search_results']

In [17]:
df_combined_web_iva_search2 = df_combined_web_iva_search[['input', 'session_id','person_internal_id',
'client_id','yyyymm','person_id','person_birth_date', 'person_age', 'person_gender', 
'person_employment_status','person_state', 'person_union_vs_non_union', 'person_salary',
'person_eeo',
'global_session_id',
'web_session_id',
'page_name',
'business_page_name',
'page_domain',
'page_type_code',
'page_type',
'page_web_type_description',
'browser_language',
'page_visit_duration',
'page_process_name',
'page_process_detail',
'session_create_date_cst_timezone_partition',
'search_text',
'search_results']]

In [18]:
df_combined_web_iva_search2.head()

,input,session_id,person_internal_id,client_id,yyyymm,person_id,person_birth_date,person_age,person_gender,person_employment_status,...,page_type_code,page_type,page_web_type_description,browser_language,page_visit_duration,page_process_name,page_process_detail,session_create_date_cst_timezone_partition,search_text,search_results
0,Benefits Eligibility For Stepchildren,943111,0,1141,201801,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Benefits Eligibility For Children,967684,319320025,8666,201801,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Benefits Eligibility For Children,997133,26800016,8053,201801,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Benefits Eligibility For Children,997133,26800016,8053,201801,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,It says we now have to verify my daughter by A...,4306768,391930089,15757,201907,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
df_combined_web_iva_search3 = df_combined_web_iva_search2.fillna('')

In [20]:
df_combined_web_iva_search3.head()

,input,session_id,person_internal_id,client_id,yyyymm,person_id,person_birth_date,person_age,person_gender,person_employment_status,...,page_type_code,page_type,page_web_type_description,browser_language,page_visit_duration,page_process_name,page_process_detail,session_create_date_cst_timezone_partition,search_text,search_results
0,Benefits Eligibility For Stepchildren,943111,0,1141,201801,,,,,,...,,,,,,,,,,
1,Benefits Eligibility For Children,967684,319320025,8666,201801,,,,,,...,,,,,,,,,,
2,Benefits Eligibility For Children,997133,26800016,8053,201801,,,,,,...,,,,,,,,,,
3,Benefits Eligibility For Children,997133,26800016,8053,201801,,,,,,...,,,,,,,,,,
4,It says we now have to verify my daughter by A...,4306768,391930089,15757,201907,,,,,,...,,,,,,,,,,

In [21]:
df_combined_web_iva_search3.columns

Index(['input', 'session_id', 'person_internal_id', 'client_id', 'yyyymm',
       'person_id', 'person_birth_date', 'person_age', 'person_gender',
       'person_employment_status', 'person_state', 'person_union_vs_non_union',
       'person_salary', 'person_eeo', 'global_session_id', 'web_session_id',
       'page_name', 'business_page_name', 'page_domain', 'page_type_code',
       'page_type', 'page_web_type_description', 'browser_language',
       'page_visit_duration', 'page_process_name', 'page_process_detail',
       'session_create_date_cst_timezone_partition', 'search_text',
       'search_results'],
      dtype='object')

In [22]:
words_2 = ['day care', 'creche', 'child care', 
 'nursery', 'nursery school', 'preschool', 'after-school care', 'day nursery', 'infant school', 
 'infant care', 'playschool', 'play-group', 'kindergarten', 'childminding', 'babysitting', 'babysitter', 
 'nanny care', 'children supervision', 'toddler care']

df_combined_web_iva_search5= df_combined_web_iva_search3[(df_combined_web_iva_search3['input'].str.contains('|'.join(words_2), case=False, na=False)) 
                                                            | (df_combined_web_iva_search3['page_name'].str.contains('|'.join(words_2), case=False, na=False))
                                                           | (df_combined_web_iva_search3['search_text'].str.contains('|'.join(words_2), case=False, na=False))]
# df_combined_web_iva_search4_2 = df_combined_web_iva_search3[df_combined_web_iva_search3['page_name'].str.contains('|'.join(words_2), case=False, na=False)]
# df_combined_web_iva_search4_3 = df_combined_web_iva_search3[df_combined_web_iva_search3['search_text'].str.contains('|'.join(words_2), case=False, na=False)]

In [23]:
df_combined_web_iva_search3.shape, df_combined_web_iva_search5.shape

((315251, 29), (245431, 29))

In [24]:
df_combined_web_iva_search5 = df_combined_web_iva_search5.sample(frac=1, random_state=42)

In [25]:
df_combined_web_iva_search5.shape

(245431, 29)

In [26]:
df_combined_non_cc_web_iva_search = df_combined_web_iva_search3[(~df_combined_web_iva_search3['input'].str.contains('|'.join(words_2), case=False, na=False))
                                                            | (~df_combined_web_iva_search3['page_name'].str.contains('|'.join(words_2), case=False, na=False))
                                                           | (~df_combined_web_iva_search3['search_text'].str.contains('|'.join(words_2), case=False, na=False))].head(df_combined_web_iva_search5.shape[0]//3)

In [27]:
df_combined_non_cc_web_iva_search = df_combined_non_cc_web_iva_search.sample(frac=1, random_state=42)

In [28]:
df_combined_cc_model_data = pd.concat([df_combined_web_iva_search5, df_combined_non_cc_web_iva_search], axis=0).sample(frac=1, random_state=42)

In [29]:
df_combined_cc_model_data.shape

(327241, 29)

### text preprocess

In [30]:
def count_intnt_entits(text):
    doc = nlp(text)
    intents = [token.text for token in doc if token.pos_ == 'VERB']
    entities = [token.text for token in doc if token.pos_ in {'NOUN', 'PROPN', 'ADJ', 'NUM', 'ADV'}]
    return len(intents), len(entities)

import re
def clean_text(text):
    clean_text = re.sub(r'[^\w\s]', '', text)
    return clean_text

def extract_ner_entities(sentence):
    doc = nlp(sentence)
    entities = [(entity.text, entity.label_) for entity in doc.ents]
    return entities

import numpy as np
def length_entities(list_entities):
    if (list_entities==np.nan or list_entities==None or list_entities==''):
        return 0
    else:
        return len(list_entities)
    
# filter_func = lambda x: any(item[1] in ["PERSON", "GPE", "ORG", "LOC", "FAC"] for item in x)
def filter_named_entities(text):
    # Process the text using Spacy
    doc = nlp(text)
    # Filter out named entities (ORG, PERSON, and GPE tags)
    filtered_words = [token.text for token in doc if token.ent_type_ not in ['ORG', 'PERSON', 'GPE', "LOC", "FAC"]]
    # Join the filtered words back into a string
    filtered_text = ' '.join(filtered_words)
    return filtered_text

In [33]:
import re
    
list_1 = ['ira','RMD','HRdirect','livechat','what is my hsa','P45','Payslip?',
    'sps','F80.2','ub','What is YSA','Paystub please','Sh','mfv','C-128','ax','no is hsa','FormL564','HIS','cif','GreT','YSACard',
    'Heli','RxPCN','403(b)','Hsa yes or no','ypr','Gv','ONA?','What is UHC?','HC-2','uo','what is 4DX?','osh','what is my hsa?',
    'sPRAVATO','sdr','RMDâ€™s','coverage?How','This is for my hsa','pto?','A&DD','childcareplus','fs','mbi','Is that my lowesbenefit.com',
    'hra yes','mri?']

def text_preprocess(dataframe, list_1):
    dataframe = dataframe.drop_duplicates()
    dataframe[['no_of_intents', 'no_of_entities']] = dataframe.apply(lambda x: pd.Series(count_intnt_entits(x['input'])), axis=1)  
    dataframe['input_cleaned'] = ''
    dataframe.loc[dataframe['input'].notnull(), 'input_cleaned'] = dataframe.loc[dataframe['input'].notnull(), 'input'].apply(clean_text)
    dataframe.loc[dataframe['page_name'].notnull(), 'page_name_cleaned'] = dataframe.loc[dataframe['page_name'].notnull(), 'page_name'].apply(clean_text)
    dataframe.loc[dataframe['search_text'].notnull(), 'search_text_cleaned'] = dataframe.loc[dataframe['search_text'].notnull(), 'search_text'].apply(clean_text)
    dataframe['ner_enities'] = ''
    dataframe.loc[dataframe['input_cleaned']!='', 'ner_enities'] = dataframe.loc[dataframe['input_cleaned']!='', 'input_cleaned'].apply(extract_ner_entities)
    dataframe['len_ner_enities'] = dataframe['ner_enities'].apply(length_entities)
    dataframe3 = dataframe[dataframe['len_ner_enities']>0]
    dataframe3['input_cleaned'] = dataframe3['input_cleaned'].apply(filter_named_entities)
    dataframe6 = pd.concat([dataframe[dataframe['len_ner_enities']==0], dataframe3], axis = 0)
    dataframe6 = dataframe6.drop(['no_of_intents','no_of_entities','ner_enities','len_ner_enities'], axis=1)
    dataframe6['input_changed']=dataframe6['input']!=dataframe6['input_cleaned']
    dataframe6['page_name_changed']=dataframe6['page_name']!=dataframe6['page_name_cleaned']
    dataframe6['search_text_changed']=dataframe6['search_text']!=dataframe6['search_text_cleaned']
    
    # create a new column 'category' containing 'Elder care' for rows where the words in words_2 appear in any of the cleaned text columns
    words_1 = ['day care', 'creche', 'child care', 
 'nursery', 'nursery school', 'preschool', 'after-school care', 'day nursery', 'infant school', 
 'infant care', 'playschool', 'play-group', 'kindergarten', 'childminding', 'babysitting', 'babysitter', 
 'nanny care', 'children supervision', 'toddler care']
    words_2 = [word.lower() for word in words_1]

    def contains_category(text):
        for word in words_2:
            pattern = r'(?<![^\W_])' + re.escape(word) + r'(?![^\W_])'
            if re.search(pattern, text.lower()):
#                 print(word)
                return True
        return False

    dataframe6['category'] = ''
    mask = (dataframe6['input_cleaned'].apply(contains_category) |
        dataframe6['page_name_cleaned'].apply(contains_category) |
        dataframe6['search_text_cleaned'].apply(contains_category)) & (dataframe6['category'] != 'Other')
    dataframe6.loc[mask, 'category'] = 'Child care'
    dataframe6.loc[dataframe6['category'] == '', 'category'] = 'Other'
    
    return dataframe6

In [34]:
df_combined_cc_model_data_2 = text_preprocess(df_combined_cc_model_data, list_1)

/tmp/ipykernel_11532/1197987153.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe[['no_of_intents', 'no_of_entities']] = dataframe.apply(lambda x: pd.Series(count_intnt_entits(x['input'])), axis=1)
/tmp/ipykernel_11532/1197987153.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe[['no_of_intents', 'no_of_entities']] = dataframe.apply(lambda x: pd.Series(count_intnt_entits(x['input'])), axis=1)
/tmp/ipykernel_11532/1197987153.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe['input_cleaned'] = ''
/tmp/ipykernel_11532/1197987153.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe.loc[dataframe['input'].notnull(), 'input_cleaned'] = dataframe.loc[dataframe['input'].notnull(), 'input'].apply(clean_text)
/tmp/ipykernel_11532/1197987153.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe.loc[dataframe['page_name'].notnull(), 'page_name_cleaned'] = dataframe.loc[dataframe['page_name'].notnull(), 'page_name'].apply(clean_text)
/tmp/ipykernel_11532/1197987153.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe.loc[dataframe['search_text'].notnull(), 'search_text_cleaned'] = dataframe.loc[dataframe['search_text'].notnull(), 'search_text'].apply(clean_text)
/tmp/ipykernel_11532/1197987153.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe['ner_enities'] = ''
/tmp/ipykernel_11532/1197987153.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe.loc[dataframe['input_cleaned']!='', 'ner_enities'] = dataframe.loc[dataframe['input_cleaned']!='', 'input_cleaned'].apply(extract_ner_entities)
/tmp/ipykernel_11532/1197987153.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe['len_ner_enities'] = dataframe['ner_enities'].apply(length_entities)
/tmp/ipykernel_11532/1197987153.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe3['input_cleaned'] = dataframe3['input_cleaned'].apply(filter_named_entities)

In [35]:
df_combined_cc_model_data_2.head(5)

,input,session_id,person_internal_id,client_id,yyyymm,person_id,person_birth_date,person_age,person_gender,person_employment_status,...,session_create_date_cst_timezone_partition,search_text,search_results,input_cleaned,page_name_cleaned,search_text_cleaned,input_changed,page_name_changed,search_text_changed,category
53934,child care plus,18043048,337550081,1487,202301,person_id,person_birth_date,41.0,person_gender,Active,...,2023-01-18,child care receipts,93.0,child care plus,HmCstmChildCarePlusLandingPageOpen,child care receipts,False,True,False,Child care
199013,child care,12010407,349300054,1487,202110,person_id,person_birth_date,36.0,person_gender,Active,...,2022-08-12,Child care,91.0,child care,HmCstmChildCarePlusLandingPageOpen,Child care,False,True,False,Child care
64747,child care,11425550,28430052,1487,202108,person_id,person_birth_date,39.0,person_gender,Active,...,2022-10-14,child care plus claim Form,143.0,child care,HmCstmChildCarePlusLandingPageOpen,child care plus claim Form,False,True,False,Child care
131979,i want to enroll for the child care help,7149313,293950071,1487,202006,,,,,,...,,child care plans,48.0,i want to enroll for the child care help,,child care plans,False,False,False,Child care
165516,Child Care Plus Information,4873539,375250047,1487,201910,person_id,person_birth_date,30.0,person_gender,Active,...,2022-08-04,Child care plus,79.0,Child Care Plus Information,HmCstmChildCarePlusLandingPageOpen,Child care plus,False,True,False,Child care

In [36]:
df_combined_cc_model_data_3 = df_combined_cc_model_data_2.drop(['person_id','person_birth_date','person_gender','global_session_id','web_session_id','business_page_name',
                                                               'page_type_code','page_type','page_web_type_description','browser_language','page_process_name',
                                                                'page_process_detail','person_eeo'], axis =1)

In [37]:
df_combined_cc_model_data_3.columns

Index(['input', 'session_id', 'person_internal_id', 'client_id', 'yyyymm',
       'person_age', 'person_employment_status', 'person_state',
       'person_union_vs_non_union', 'person_salary', 'page_name',
       'page_domain', 'page_visit_duration',
       'session_create_date_cst_timezone_partition', 'search_text',
       'search_results', 'input_cleaned', 'page_name_cleaned',
       'search_text_cleaned', 'input_changed', 'page_name_changed',
       'search_text_changed', 'category'],
      dtype='object')

In [38]:
df_combined_cc_model_data_3 = df_combined_cc_model_data_3[[ 'session_id', 'person_internal_id', 'client_id', 'input','input_cleaned',
                                                            'search_text','search_text_cleaned', 'page_name','page_name_cleaned',
                                                           'category','person_age',
        'person_employment_status', 'person_state',
       'person_union_vs_non_union', 'person_salary',
       'page_domain', 'page_visit_duration',
       'session_create_date_cst_timezone_partition',
       'search_results', 'yyyymm',
        'input_changed', 'page_name_changed',
       'search_text_changed']]

In [39]:
df_combined_cc_model_data_3.to_excel('cc_model_combined_cleaned_data_v1.xlsx')

In [40]:
df_combined_cc_model_data_3.dtypes

session_id                                     int64
person_internal_id                             int64
client_id                                      int64
input                                         object
input_cleaned                                 object
search_text                                   object
search_text_cleaned                           object
page_name                                     object
page_name_cleaned                             object
category                                      object
person_age                                    object
person_employment_status                      object
person_state                                  object
person_union_vs_non_union                     object
person_salary                                 object
page_domain                                   object
page_visit_duration                           object
session_create_date_cst_timezone_partition    object
search_results                                object
yyyymm                                         int64
input_changed                                   bool
page_name_changed                               bool
search_text_changed                             bool
dtype: object

In [41]:
df_combined_cc_model_data_4 = df_combined_cc_model_data_3.drop(['input','search_text','page_name','input_changed','page_name_changed',
                                                               'search_text_changed'], axis=1)

In [42]:
df_combined_cc_model_data_5 = df_combined_cc_model_data_4.copy()

In [43]:
df_combined_cc_model_data_5[['person_age','person_salary','page_visit_duration']] = df_combined_cc_model_data_4[['person_age','person_salary','page_visit_duration']].apply(pd.to_numeric,errors='coerce')
# combined_ec_model_data_5['person_salary'] = df_combined_ec_model_data_4['person_salary'].to_numeric()
# combined_ec_model_data_5['page_visit_duration'] = df_combined_ec_model_data_4['page_visit_duration'].to_numeric()
# .astype({"person_age": float, "person_salary": float, "page_visit_duration": float })

In [44]:
df_combined_cc_model_data_5['session_create_date_cst_timezone_partition'] = pd.to_datetime(
    df_combined_cc_model_data_4['session_create_date_cst_timezone_partition'])

In [45]:
df_combined_cc_model_data_5.shape

(253254, 17)

In [46]:
df_combined_cc_model_data_5.to_excel('final_cc_model_data.xlsx')

### Model building on the basis of just text columns

------

In [47]:
import pandas as pd

In [48]:
# Load the data
data = pd.read_excel('final_cc_model_data.xlsx')[['input_cleaned', 'search_text_cleaned', 'page_name_cleaned', 'category']]
data.sample()

,input_cleaned,search_text_cleaned,page_name_cleaned,category
131608,child care,Child care plus,HmCstmChildCarePlusLandingPageOpen,Child care

In [49]:
data.fillna(value={'input_cleaned': ' ', 'page_name_cleaned': ' ', 'search_text_cleaned': ' '}, inplace=True)

In [50]:
data.sample()

,input_cleaned,search_text_cleaned,page_name_cleaned,category
83753,I am trying to find Child Care Plus,childcare,,Child care

In [51]:
data.category.value_counts()

Child care    232086
Other          21168
Name: category, dtype: int64

In [52]:
data.category = data.category.map({'Other':0, 'Child care':1})
data.sample()

,input_cleaned,search_text_cleaned,page_name_cleaned,category
234226,One of my dependent children not showing up wh...,,HmCstmChildCarePlusLandingPageOpen,1

In [53]:
from sklearn.model_selection import train_test_split

# split the dataset into training and testing sets
data, unseen_data = train_test_split(data, test_size=0.1, random_state=6)
unseen_data.to_excel('unseen_data.xlsx')

In [ ]:
import pandas as pd
import numpy as np
import torch
from sklearn.metrics import accuracy_score, confusion_matrix
from transformers import BertTokenizer, BertForSequenceClassification

# set the random seed for NumPy
np.random.seed(42)

# set the random seed for PyTorch
torch.manual_seed(42)

# load the data
# data = pd.read_csv('data.csv')

# load the BERT tokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

# encode the data using the tokenizer
encodings = tokenizer(list(data['input_cleaned']), list(data['search_text_cleaned']), list(data['page_name_cleaned']),
                      truncation=True, padding=True)

# create the dataset
dataset = torch.utils.data.TensorDataset(
    torch.tensor(encodings['input_ids']),
    torch.tensor(encodings['attention_mask']),
    torch.tensor(list(data['category']))
)

# split the dataset into training and validation sets
train_size = int(0.8 * len(dataset))
val_size = len(dataset) - train_size
train_dataset, val_dataset = torch.utils.data.random_split(dataset, [train_size, val_size])

# create the DataLoader for the training and validation sets
train_loader = torch.utils.data.DataLoader(train_dataset, batch_size=16, shuffle=True)
val_loader = torch.utils.data.DataLoader(val_dataset, batch_size=16, shuffle=False)

# load the BERT model for sequence classification
model = BertForSequenceClassification.from_pretrained('bert-base-uncased', num_labels=2,)

# set up the optimizer and loss function
optimizer = torch.optim.AdamW(model.parameters(), lr=2e-5)
loss_fn = torch.nn.CrossEntropyLoss()

epochs=5

# train the model
for epoch in range(epochs):
    running_loss = 0.0
    for batch in train_loader:
        input_ids, attention_mask, labels = batch
        outputs = model(input_ids, attention_mask=attention_mask, labels=labels)
        loss = outputs.loss
        logits = outputs.logits
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()
        running_loss += loss.item()
    print(f'Epoch {epoch + 1} Loss: {running_loss / len(train_loader)}')

    # make predictions on the validation set and compute the accuracy
    predictions = []
    true_labels = []
    with torch.no_grad():
        model.eval()
        for batch in val_loader:
            input_ids, attention_mask, labels = batch
            outputs = model(input_ids, attention_mask=attention_mask)
            logits = outputs.logits
            predictions.extend(torch.argmax(logits, dim=1).tolist())
            true_labels.extend(labels.tolist())

    accuracy = accuracy_score(true_labels, predictions)
    print(f'Epoch {epoch + 1} Validation Accuracy: {accuracy}')

    # generate the confusion matrix
    cm = confusion_matrix(true_labels, predictions)
    print(f'Epoch {epoch + 1} Confusion Matrix:')
    print(cm)

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForSequenceClassification: ['cls.seq_relationship.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Epoch 1 Loss: 0.008136592370417613
Epoch 1 Validation Accuracy: 0.9985521870749792
Epoch 1 Confusion Matrix:
[[ 3719    24]
 [   42 41801]]

In [ ]:
# define the path to save the model
save_path = "./CC_model_combined_texts_data/"

# create the directory if it doesn't exist
import os
if not os.path.exists(save_path):
    os.makedirs(save_path)

# save the model
model.save_pretrained(save_path)

## prediction code

In [ ]:
import pandas as pd
import torch
from transformers import BertTokenizer, BertForSequenceClassification

# load the BERT tokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

# load the trained model
model = BertForSequenceClassification.from_pretrained(save_path)

# load the new data to be predicted
new_data = pd.read_excel('unseen_data.xlsx')

# encode the new data using the tokenizer
encodings = tokenizer(list(new_data['input_cleaned']), list(new_data['search_text_cleaned']), list(new_data['page_name_cleaned']),
                      truncation=True, padding=True)

# create the dataset
dataset = torch.utils.data.TensorDataset(
    torch.tensor(encodings['input_ids']),
    torch.tensor(encodings['attention_mask'])
)

# create the DataLoader for the new data
loader = torch.utils.data.DataLoader(dataset, batch_size=16, shuffle=False)

# make predictions on the new data
predictions = []
with torch.no_grad():
    model.eval()
    for batch in loader:
        input_ids, attention_mask = batch
        outputs = model(input_ids, attention_mask=attention_mask)
        logits = outputs.logits
        predictions.extend(torch.argmax(logits, dim=1).tolist())

# add the predictions to the new data DataFrame
new_data['predictions'] = predictions

# save the new data with predictions
new_data.to_csv('CC_predictions.csv', index=False)